In [93]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [94]:
data = pd.read_csv("train.csv")

In [95]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [96]:
data.shape

(42000, 785)

In [106]:
data = np.array(data)
m,n = data.shape
np.random.shuffle(data)

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev/255

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train/255

In [107]:
Y_train

array([2, 4, 0, ..., 2, 8, 0], dtype=int64)

In [108]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [109]:
Y_train.shape, X_train.shape

((41000,), (784, 41000))

In [137]:
def init_params():
    W1 = np.random.rand(10, 784)-0.5
    b1 = np.random.rand(10, 1)-0.5
    W2 = np.random.rand(10, 10)-0.5
    b2 = np.random.rand(10, 1)-0.5
    return W1, b1, W2, b2
def ReLU(Z):
    return np.maximum(0,Z)

def deriv_ReLU(Z):
    return Z>0

def softmax(Z):
    A = np.exp(Z)/sum(np.exp(Z))
    return A

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def back_prop(Z1, A1, Z2, A2, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha*dW1
    b1 = b1 - alpha*db1
    W2 = W2 - alpha*dW2
    b2 = b2 - alpha*db2
    return W1, b1, W2, b2

In [138]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y)/Y.size

def gradient_descent(X, Y, iterations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2 ,W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i%10==0:
            print("Iteration: ",i)
            print("Accuracy: ", get_accuracy(get_predictions(A2), Y))
    return W1, b1, W2, b2

In [140]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 500, 0.2)

Iteration:  0
[4 1 7 ... 1 9 7] [2 4 0 ... 2 8 0]
Accuracy:  0.09026829268292683
Iteration:  10
[1 1 0 ... 4 3 0] [2 4 0 ... 2 8 0]
Accuracy:  0.3038292682926829
Iteration:  20
[1 2 0 ... 4 3 0] [2 4 0 ... 2 8 0]
Accuracy:  0.4058048780487805
Iteration:  30
[1 4 0 ... 8 3 0] [2 4 0 ... 2 8 0]
Accuracy:  0.4938780487804878
Iteration:  40
[1 4 0 ... 8 3 0] [2 4 0 ... 2 8 0]
Accuracy:  0.5861463414634146
Iteration:  50
[1 4 0 ... 8 3 0] [2 4 0 ... 2 8 0]
Accuracy:  0.6519024390243903
Iteration:  60
[1 4 0 ... 8 3 0] [2 4 0 ... 2 8 0]
Accuracy:  0.689
Iteration:  70
[1 4 0 ... 1 3 0] [2 4 0 ... 2 8 0]
Accuracy:  0.715390243902439
Iteration:  80
[1 4 0 ... 1 3 0] [2 4 0 ... 2 8 0]
Accuracy:  0.7338536585365854
Iteration:  90
[1 4 0 ... 2 3 0] [2 4 0 ... 2 8 0]
Accuracy:  0.748390243902439
Iteration:  100
[1 4 0 ... 2 5 0] [2 4 0 ... 2 8 0]
Accuracy:  0.761390243902439
Iteration:  110
[1 4 0 ... 2 5 0] [2 4 0 ... 2 8 0]
Accuracy:  0.7720243902439025
Iteration:  120
[1 4 0 ... 2 5 0] [2 4 0 .